name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React application
        run: npm run build

      - name: Check build status
        run: |
          if [ -d "build" ]; then
            echo "Build successful"
          else
            echo "Build failed"
            exit 1
          fi
